name: context
description: The Context library provides a comprehensive set of tools for managing and transferring application context efficiently.
version: 1.0.0
homepage: https://github.com/F1rrock/context
repository: https://github.com/F1rrock/context

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
